using Newtonsoft.Json;

namespace CousinPCMS.Domain
{
    public class ItemResponseModel
    {
        [JsonProperty("@odata.etag")]
        public string ODataEtag { get; set; }
        public string ItemNumber { get; set; }
        public string SkuName { get; set; }
        public int PriceUnitConversion { get; set; }
        public string InventoryPostingGroup { get; set; }
        public string ShelfNo { get; set; }
        public string ItemDiscGroup { get; set; }
        public bool AllowInvoiceDisc { get; set; }
        public int StatisticsGroup { get; set; }
        public int CommissionGroup { get; set; }
        public decimal UnitPrice { get; set; }
        public string PriceProfitCalculation { get; set; }
        public decimal Profit { get; set; }
        public decimal UnitCost { get; set; }
        public decimal StandardCost { get; set; }
        public decimal LastDirectCost { get; set; }
        public decimal IndirectCost { get; set; }
        public bool CostIsAdjusted { get; set; }
        public bool AllowOnlineAdjustment { get; set; }
        public string LeadTimeCalculation { get; set; }
        public int ReorderPoint { get; set; }
        public int MaximumInventory { get; set; }
        public int ReorderQuantity { get; set; }
        public string AlternativeItemNo { get; set; }
        public decimal UnitListPrice { get; set; }
        public decimal DutyDue { get; set; }
        public string DutyCode { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal NetWeight { get; set; }
        public int UnitsPerParcel { get; set; }
        public decimal UnitVolume { get; set; }
        public string Durability { get; set; }
        public string FreightType { get; set; }
        public string TariffNo { get; set; }
        public int DutyUnitConversion { get; set; }
        public string CountryRegionPurchasedCode { get; set; }
        public decimal BudgetQuantity { get; set; }
        public decimal BudgetedAmount { get; set; }
        public decimal BudgetProfit { get; set; }
        public bool Blocked { get; set; }
        public string BlockReason { get; set; }
        public DateTime LastDateTimeModified { get; set; }
        public DateTime LastDateModified { get; set; }
        public string LastTimeModified { get; set; }
        public bool PriceIncludesVAT { get; set; }
        public string VatBusPostingGrPrice { get; set; }
        public string GenProdPostingGroup { get; set; }
        public Guid Picture { get; set; }
        public string CountryRegionOfOriginCode { get; set; }
        public bool AutomaticExtTexts { get; set; }
        public string NoSeries { get; set; }
        public string TaxGroupCode { get; set; }
        public string VatProdPostingGroup { get; set; }
        public string Reserve { get; set; }
        public string GlobalDimension1Code { get; set; }
        public string GlobalDimension2Code { get; set; }
        public string StockoutWarning { get; set; }
        public string PreventNegativeInventory { get; set; }
        public string VariantMandatoryIfExists { get; set; }
        public string ApplicationWkshUserID { get; set; }
        public bool CoupledToCRM { get; set; }
        public string Gtin { get; set; }
        public string DefaultDeferralTemplateCode { get; set; }
        public int LowLevelCode { get; set; }
        public int LotSize { get; set; }
        public string SerialNos { get; set; }
        public DateTime LastUnitCostCalcDate { get; set; }
        public decimal RolledUpMaterialCost { get; set; }
        public decimal RolledUpCapacityCost { get; set; }
        public decimal Scrap { get; set; }
        public bool InventoryValueZero { get; set; }
        public int DiscreteOrderQuantity { get; set; }
        public int MinimumOrderQuantity { get; set; }
        public int MaximumOrderQuantity { get; set; }
        public int SafetyStockQuantity { get; set; }
        public int OrderMultiple { get; set; }
        public string SafetyLeadTime { get; set; }
        public string FlushingMethod { get; set; }
        public string ReplenishmentSystem { get; set; }
        public int RoundingPrecision { get; set; }
        public string PurchUnitOfMeasure { get; set; }
        public string TimeBucket { get; set; }
        public string ReorderingPolicy { get; set; }
        public bool IncludeInventory { get; set; }
        public string ManufacturingPolicy { get; set; }
        public string ReschedulingPeriod { get; set; }
        public string LotAccumulationPeriod { get; set; }
        public string DampenerPeriod { get; set; }
        public decimal DampenerQuantity { get; set; }
        public decimal OverflowLevel { get; set; }
        public string ManufacturerCode { get; set; }
        public bool CreatedFromNonstockItem { get; set; }
        public string PurchasingCode { get; set; }
        public bool ExcludedFromCostAdjustment { get; set; }
        public string ServiceItemGroup { get; set; }
        public string ItemTrackingCode { get; set; }
        public string LotNos { get; set; }
        public string ExpirationCalculation { get; set; }
        public string WarehouseClassCode { get; set; }
        public string SpecialEquipmentCode { get; set; }
        public string PutAwayTemplateCode { get; set; }
        public string PutAwayUnitOfMeasureCode { get; set; }
        public string PhysInvtCountingPeriodCode { get; set; }
        public DateTime LastCountingPeriodUpdate { get; set; }
        public bool UseCrossDocking { get; set; }
        public DateTime NextCountingStartDate { get; set; }
        public DateTime NextCountingEndDate { get; set; }
        public Guid UnitOfMeasureId { get; set; }
        public Guid TaxGroupId { get; set; }
        public bool SalesBlocked { get; set; }
        public bool PurchasingBlocked { get; set; }
        public Guid ItemCategoryId { get; set; }
        public Guid InventoryPostingGroupId { get; set; }
        public Guid GenProdPostingGroupId { get; set; }
        public bool ServiceBlocked { get; set; }
        public string OverReceiptCode { get; set; }
        public string AssemblyPolicy { get; set; }
        public string RoutingNo { get; set; }
        public string ProductionBOMNo { get; set; }
    }
}
