using Newtonsoft.Json;

namespace CousinPCMS.Domain
{
    public class ItemResponseModel
    {
        [JsonProperty("@odata.etag")]
        public string odataetag { get; set; }
        public string akiitemid { get; set; }
        public string skuName { get; set; }
        public int priceUnitConversion { get; set; }
        public string inventoryPostingGroup { get; set; }
        public string shelfNo { get; set; }
        public string itemDiscGroup { get; set; }
        public bool allowInvoiceDisc { get; set; }
        public int statisticsGroup { get; set; }
        public int commissionGroup { get; set; }
        public int unitPrice { get; set; }
        public string priceProfitCalculation { get; set; }
        public int profit { get; set; }
        public double unitCost { get; set; }
        public int standardCost { get; set; }
        public int lastDirectCost { get; set; }
        public int indirectCost { get; set; }
        public bool costIsAdjusted { get; set; }
        public bool allowOnlineAdjustment { get; set; }
        public string leadTimeCalculation { get; set; }
        public int reorderPoint { get; set; }
        public int maximumInventory { get; set; }
        public int reorderQuantity { get; set; }
        public string alternativeItemNo { get; set; }
        public int unitListPrice { get; set; }
        public int dutyDue { get; set; }
        public string dutyCode { get; set; }
        public int grossWeight { get; set; }
        public int netWeight { get; set; }
        public int unitsPerParcel { get; set; }
        public int unitVolume { get; set; }
        public string durability { get; set; }
        public string freightType { get; set; }
        public string tariffNo { get; set; }
        public int dutyUnitConversion { get; set; }
        public string countryRegionPurchasedCode { get; set; }
        public int budgetQuantity { get; set; }
        public int budgetedAmount { get; set; }
        public int budgetProfit { get; set; }
        public bool blocked { get; set; }
        public string blockReason { get; set; }
        public DateTime lastDateTimeModified { get; set; }
        public string lastDateModified { get; set; }
        public string lastTimeModified { get; set; }
        public bool priceIncludesVAT { get; set; }
        public string vatBusPostingGrPrice { get; set; }
        public string genProdPostingGroup { get; set; }
        public string picture { get; set; }
        public string countryRegionOfOriginCode { get; set; }
        public bool automaticExtTexts { get; set; }
        public string noSeries { get; set; }
        public string taxGroupCode { get; set; }
        public string vatProdPostingGroup { get; set; }
        public string reserve { get; set; }
        public string globalDimension1Code { get; set; }
        public string globalDimension2Code { get; set; }
        public string stockoutWarning { get; set; }
        public string preventNegativeInventory { get; set; }
        public string variantMandatoryIfExists { get; set; }
        public string applicationWkshUserID { get; set; }
        public bool coupledToCRM { get; set; }
        public string gtin { get; set; }
        public string defaultDeferralTemplateCode { get; set; }
        public int lowLevelCode { get; set; }
        public int lotSize { get; set; }
        public string serialNos { get; set; }
        public string lastUnitCostCalcDate { get; set; }
        public int rolledUpMaterialCost { get; set; }
        public int rolledUpCapacityCost { get; set; }
        public int scrap { get; set; }
        public bool inventoryValueZero { get; set; }
        public int discreteOrderQuantity { get; set; }
        public int minimumOrderQuantity { get; set; }
        public int maximumOrderQuantity { get; set; }
        public int safetyStockQuantity { get; set; }
        public int orderMultiple { get; set; }
        public string safetyLeadTime { get; set; }
        public string flushingMethod { get; set; }
        public string replenishmentSystem { get; set; }
        public int roundingPrecision { get; set; }
        public string purchUnitOfMeasure { get; set; }
        public string timeBucket { get; set; }
        public string reorderingPolicy { get; set; }
        public bool includeInventory { get; set; }
        public string manufacturingPolicy { get; set; }
        public string reschedulingPeriod { get; set; }
        public string lotAccumulationPeriod { get; set; }
        public string dampenerPeriod { get; set; }
        public int dampenerQuantity { get; set; }
        public int overflowLevel { get; set; }
        public string manufacturerCode { get; set; }
        public bool createdFromNonstockItem { get; set; }
        public string purchasingCode { get; set; }
        public bool excludedFromCostAdjustment { get; set; }
        public string serviceItemGroup { get; set; }
        public string itemTrackingCode { get; set; }
        public string lotNos { get; set; }
        public string expirationCalculation { get; set; }
        public string warehouseClassCode { get; set; }
        public string specialEquipmentCode { get; set; }
        public string putAwayTemplateCode { get; set; }
        public string putAwayUnitOfMeasureCode { get; set; }
        public string physInvtCountingPeriodCode { get; set; }
        public string lastCountingPeriodUpdate { get; set; }
        public bool useCrossDocking { get; set; }
        public string nextCountingStartDate { get; set; }
        public string nextCountingEndDate { get; set; }
        public string unitOfMeasureId { get; set; }
        public string taxGroupId { get; set; }
        public bool salesBlocked { get; set; }
        public bool purchasingBlocked { get; set; }
        public string itemCategoryId { get; set; }
        public string inventoryPostingGroupId { get; set; }
        public string genProdPostingGroupId { get; set; }
        public bool serviceBlocked { get; set; }
        public string overReceiptCode { get; set; }
        public string assemblyPolicy { get; set; }
        public string routingNo { get; set; }
        public string productionBOMNo { get; set; }
        public int singleLevelMaterialCost { get; set; }
        public int singleLevelCapacityCost { get; set; }
        public int singleLevelSubcontrdCost { get; set; }
        public int singleLevelCapOvhdCost { get; set; }
        public int singleLevelMfgOvhdCost { get; set; }
        public int overheadRate { get; set; }
        public int rolledUpSubcontractedCost { get; set; }
        public int rolledUpMfgOvhdCost { get; set; }
        public int rolledUpCapOverheadCost { get; set; }
        public bool critical { get; set; }
        public string commonItemNo { get; set; }
        public string no2 { get; set; }
        public string searchDescription { get; set; }
        public string description2 { get; set; }
        public int akiSKUID { get; set; }
        public string akiProductID { get; set; }
        public string akiCategoryID { get; set; }
        public string akiSKUDescription { get; set; }
        public string akiManufacturerRef { get; set; }
        public int akiListOrder { get; set; }
        public bool akiObsolete { get; set; }
        public bool akiWebActive { get; set; }
        public string akiImageURL { get; set; }
        public string akiCommodityCode { get; set; }
        public int akiGuidePriceTBC { get; set; }
        public int akiGuideWeightTBC { get; set; }
        public bool akiSKUIsActive { get; set; }
        public bool akiCurrentlyPartRestricted { get; set; }
        public string akiCountryOfOrigin { get; set; }
        public bool akiPrintLayoutTemp { get; set; }
        public string akiAlternativeTitle { get; set; }
        public string akiCompetitors { get; set; }
        public bool akiPriceBreaksTBC { get; set; }
        public string itemclasscode { get; set; }
        public int akiItemShippingWeight { get; set; }
        public string itemUOfMeasureScheduleID { get; set; }
        public string itemsellingUOfM { get; set; }
        public string itemsupplierID { get; set; }
        public string itemcreditoritemno { get; set; }
        public string akiItemSiteID { get; set; }
        public int akiItemPriceWebsiteSellPrice { get; set; }
        public int itemstartingquantity { get; set; }
        public string itemtype { get; set; }
        public string itemvaluationMethod { get; set; }
        public int akiItemPriceSiteSellPrice { get; set; }
        public string akiItemShortDescription { get; set; }
        public int akiTemplateID { get; set; }
        public string akiAltSKUName { get; set; }
        public string akiLayoutTemplate { get; set; }
        public string akiPricingFormula { get; set; }
        public string akiPriceBreak { get; set; }
        public string akiPriceGroup { get; set; }
    }

    public class AddItemRequestModel
    {
        public string akiitemid { get; set; }
        public string skuName { get; set; }
        public int akiSKUID { get; set; }
        public string akiProductID { get; set; }
        public string akiCategoryID { get; set; }
        public string akiManufacturerRef { get; set; }
        public int akiListOrder { get; set; }
        public bool akiObsolete { get; set; }
        public bool akiWebActive { get; set; }
        public string akiImageURL { get; set; }
        public string akiCommodityCode { get; set; }
        public int akiGuidePriceTBC { get; set; }
        public int akiGuideWeightTBC { get; set; }
        public bool akicurrentlyPartRestricted { get; set; }
        public string akiCountryofOrigin { get; set; }
        public bool akiPrintLayoutTemp { get; set; }
        public string akiAlternativeTitle { get; set; }
        public string akiCompetitors { get; set; }
        public bool akiPriceBreaksTBC { get; set; }
        public int akiItemShippingWeight { get; set; }
        public int akiItemPriceSiteSellPrice { get; set; }
        public int akiTemplateID { get; set; }
        public string akiLayoutTemplate { get; set; }
        public string akiSKUDescription { get; set; }
        public string akiPricingFormula { get; set; }
        public string akiPriceBreak { get; set; }
        public string akiPriceGroup { get; set; }
    }

}
